# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.post_voter:
          class:  CA\BlogBundle\Security\Voter\BlogVoter
          arguments: ['@security.access.decision_manager']
          tags:
              - { name: security.voter }
          # small performance boost
          public: false
    app.user_voter:
              class:  CA\BlogBundle\Security\Voter\UserVoter
              arguments: ['@security.access.decision_manager']
              tags:
                  - { name: security.voter }
              # small performance boost
              public: false
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
