<?php

namespace CA\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByCategories($slug)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->add('select', 'a');
        $qb->leftJoin('a.category', 'c');
        $qb->where('c.name LIKE :category'); 
        $qb->setParameter('category', $slug);
        $qb->getQuery()->getResult();

        return $qb;
    }
}
