post_index:
    path:     /
    defaults: { _controller: "CABlogBundle:Post:index" }
    methods:  GET

post_show:
    path:     /{id}/show
    defaults: { _controller: "CABlogBundle:Post:show" }
    requirements:
        id:   \d+
    methods:  GET

post_show_bis:
    path:     /{title}/show
    defaults: { _controller: "CABlogBundle:Post:showTitle" }
    requirements:
        title:   \w+
    methods:  GET

post_new:
    path:     /new
    defaults: { _controller: "CABlogBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "CABlogBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "CABlogBundle:Post:delete" }
    methods:  DELETE
